# Generated by Django 3.1.7 on 2021-03-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210331_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='website',
            new_name='web_site',
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
